version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass

  shareit-server:
    build: server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  shareit-gateway:
    build: gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - shareit-server
    environment:
      - SHAREIT_SERVER_URL=http://shareit-server:9090